/**
 * Chat: MessageBubble — Renders user, assistant, and system messages.
 * Supports: text, voice transcription, genui, images, tool calls/responses.
 */

import { lazy, Suspense } from 'react';
import { cn } from '@/lib/cn';
import { Mic, Bot, Image, AlertCircle, Smartphone, FileCode } from 'lucide-react';
import ActionCard from '@/components/chat/ActionCard';
import MarkdownContent from '@/components/chat/MarkdownContent';

const GenUIRenderer = lazy(() => import('@/components/genui/GenUIRenderer'));
const GenUIModal = lazy(() => import('@/components/genui/GenUIModal'));

export default function MessageBubble({ message }) {
  if (!message) return null;
  const { role, type, content, content_type, source } = message;

  // ── Action card (tool call/response, agent transfer) ───────────
  if (type === 'action' || type === 'agent_transfer') return <ActionCard action={message} />;

  // ── Legacy tool call / response (backwards compat) ─────────────
  if (type === 'tool_call') return <ActionCard action={{ ...message, type: 'action' }} />;
  if (type === 'tool_response') return <ActionCard action={{ ...message, type: 'action', responded: true }} />;

  // ── Error message ───────────────────────────────────────────────
  if (type === 'error') {
    return (
      <div className="flex justify-start mb-3">
        <div className="flex items-start gap-2 max-w-[80%] rounded-2xl px-4 py-2.5 text-sm bg-destructive/10 border border-destructive/30 text-destructive">
          <AlertCircle size={15} className="mt-0.5 flex-shrink-0" />
          <span>{content}</span>
        </div>
      </div>
    );
  }

  // ── Companion card (rich content alongside voice — code, tables) ──
  if (content_type === 'companion') {
    return (
      <div className="flex justify-start mb-3">
        <div className="mr-2 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-blue-500/10 text-blue-500">
          <FileCode size={14} />
        </div>
        <div className="max-w-[85%] rounded-2xl border border-blue-500/20 bg-blue-500/5 px-4 py-3">
          <MarkdownContent content={content} />
        </div>
      </div>
    );
  }

  // ── Image generated by the agent ───────────────────────────────
  if (type === 'image') return <ImageBubble message={message} />;

  const isUser = role === 'user';
  const isVoice = source === 'voice';
  const isCrossClient = message.cross_client === true;

  return (
    <div className={cn('flex mb-3 group', isUser ? 'justify-end' : 'justify-start')}>
      {/* Avatar */}
      {!isUser && (
        <div className="mr-2.5 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full border border-white/[0.08] bg-white/[0.04] text-foreground/70">
          <Bot size={14} />
        </div>
      )}

      <div className={cn('max-w-[80%] space-y-2')}>
        {/* Source badge */}
        {(isVoice || isCrossClient) && (
          <span className={cn(
            'inline-flex items-center gap-1 text-[10px] text-muted-foreground/60',
            isUser ? 'float-right' : '',
          )}>
            {isCrossClient
              ? <><Smartphone size={10} /> other device</>
              : <><Mic size={10} /> voice</>
            }
          </span>
        )}

        {/* Text content — uses markdown rendering for code/tables/lists */}
        {content && content_type !== 'genui' && (
          <div
            className={cn(
              'rounded-2xl px-4 py-2.5 text-sm leading-relaxed',
              isUser
                ? 'bg-foreground text-background'
                : isCrossClient
                  ? 'bg-violet-500/5 border border-violet-500/20 text-foreground'
                  : 'bg-white/[0.04] border border-white/[0.06] text-foreground/90',
            )}
          >
            {isUser ? content : <MarkdownContent content={content} />}
          </div>
        )}

        {/* GenUI block — inline in chat with expand-to-modal */}
        {message.genui_type && message.genui_data && (
          <div className="rounded-xl border border-white/[0.06] bg-white/[0.03] p-3 shadow-sm">
            <Suspense fallback={<div className="h-20 animate-pulse rounded bg-muted" />}>
              <GenUIModal type={message.genui_type} data={message.genui_data} />
            </Suspense>
          </div>
        )}

        {/* Image content */}
        {content_type === 'image' && message.image_url && (
          <img
            src={message.image_url}
            alt="Shared image"
            className="max-h-64 rounded-xl border border-white/[0.06] object-cover"
          />
        )}

        {/* Timestamp */}
        <p className={cn(
          'text-[10px] text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100',
          isUser ? 'text-right' : 'text-left',
        )}>
          {message.timestamp ? new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''}
        </p>
      </div>

      {/* User avatar */}
      {isUser && (
        <div className="ml-2.5 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-foreground text-background text-xs font-bold">
          U
        </div>
      )}
    </div>
  );
}

function ImageBubble({ message }) {
  const {
    image_base64, image_url = '', mime_type = 'image/png', description,
    images = [], text, parts = [],
  } = message;

  // ── Interleaved mode (generate_rich_image) ─────────────────────
  // When `parts` is populated, render text and images in the original
  // order Gemini produced them (illustrated guide pattern).
  if (parts.length > 0) {
    return (
      <div className="mb-3 flex justify-start">
        <div className="mr-2 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary">
          <Image size={14} />
        </div>
        <div className="max-w-[80%] space-y-2">
          {parts.map((part, i) =>
            part.type === 'text' ? (
              <div
                key={i}
                className="rounded-2xl bg-muted/60 backdrop-blur-sm border border-border/40 px-4 py-2.5 text-sm leading-relaxed whitespace-pre-wrap"
              >
                {part.content}
              </div>
            ) : part.type === 'image' && (part.base64 || (part.image_url && !part.image_url.startsWith('gs://'))) ? (
              <div key={i} className="overflow-hidden rounded-xl border border-border/40 bg-muted/20">
                <img
                  src={part.base64 ? `data:${part.mime_type || 'image/png'};base64,${part.base64}` : part.image_url}
                  alt="Generated illustration"
                  className="max-h-96 w-full object-contain"
                />
              </div>
            ) : null,
          )}
        </div>
      </div>
    );
  }

  // ── Single image mode (generate_image) ─────────────────────────
  const allImages = [];
  if (image_base64) {
    allImages.push({ src: `data:${mime_type};base64,${image_base64}`, caption: description });
  } else if (image_url && !image_url.startsWith('gs://')) {
    allImages.push({ src: image_url, caption: description });
  }
  for (const img of images) {
    if (img.base64) {
      allImages.push({ src: `data:${img.mime_type || 'image/png'};base64,${img.base64}`, caption: '' });
    } else if (img.url && !img.url.startsWith('gs://')) {
      allImages.push({ src: img.url, caption: '' });
    }
  }

  if (allImages.length === 0 && !text) return null;

  return (
    <div className="mb-3 flex justify-start">
      <div className="mr-2 flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary">
        <Image size={14} />
      </div>
      <div className="max-w-[80%] space-y-2">
        {text && (
          <div className="rounded-2xl bg-muted/60 backdrop-blur-sm border border-border/40 px-4 py-2.5 text-sm leading-relaxed">
            {text}
          </div>
        )}
        {allImages.map((img, i) => (
          <div key={i} className="overflow-hidden rounded-xl border border-border/40 bg-muted/20">
            <img
              src={img.src}
              alt={img.caption || 'Generated image'}
              className="max-h-96 w-full object-contain"
            />
            {img.caption && (
              <p className="px-3 py-1.5 text-xs text-muted-foreground">{img.caption}</p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
